### ISSUE TITLE
Expert Predictions

### ISSUE THREAD

**Issue by jonthegeek** [simonschoe/ml-with-tidymodels#1]
About a year ago you opened this issue on the stacks package: https://github.com/tidymodels/stacks/issues/91

The issue is locked, so I can't reply to it, but I wanted to ping you to let you know that I made a thing that MIGHT address it: https://github.com/macmillancontentscience/bespoke

Let me know if it looks like that would do what you were thinking!

**Comment by simonschoe** [comment]
Hi @jonthegeek, that was indeed the thing I was looking for back then. By now I found a workaround or simply skipped on the issue (I do not quite remember honestly). However, thanks for the pointer, I am sure I'll face a similar case again in the future!
